/**
 * useDailyBriefing.ts
 *
 * Manages the AI-generated daily executive briefing.
 *
 * - Checks localStorage for a cached briefing from today.
 * - If none exists, auto-generates on first call when messages are available.
 * - Provides a `generate()` function to manually refresh.
 * - Caches the result in localStorage keyed by uid + date so the briefing
 *   survives page reloads without burning tokens.
 */

"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { auth } from "@/lib/firebase";
import type { Message } from "@/lib/mock-data";

const CACHE_KEY_PREFIX = "nexaro_daily_briefing";
const MAX_MESSAGES = 30;

export interface DailyBriefingState {
    briefing: string | null;
    generatedAt: string | null;
    isGenerating: boolean;
    error: string | null;
}

export interface UseDailyBriefingResult extends DailyBriefingState {
    generate: () => Promise<void>;
}

function todayKey(uid: string): string {
    const date = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
    return `${CACHE_KEY_PREFIX}_${uid}_${date}`;
}

interface CachedBriefing {
    briefing: string;
    generatedAt: string;
}

function loadCached(uid: string): CachedBriefing | null {
    if (typeof window === "undefined") return null;
    try {
        const raw = localStorage.getItem(todayKey(uid));
        if (!raw) return null;
        return JSON.parse(raw) as CachedBriefing;
    } catch {
        return null;
    }
}

function saveCache(uid: string, data: CachedBriefing): void {
    if (typeof window === "undefined") return;
    try {
        localStorage.setItem(todayKey(uid), JSON.stringify(data));
    } catch {
        // localStorage full — ignore
    }
}

export function useDailyBriefing(
    uid: string | null,
    allMessages: Message[],
): UseDailyBriefingResult {
    const [state, setState] = useState<DailyBriefingState>({
        briefing: null,
        generatedAt: null,
        isGenerating: false,
        error: null,
    });

    const autoGeneratedRef = useRef(false);

    // Load cached briefing on mount / uid change
    useEffect(() => {
        if (!uid) {
            setState({ briefing: null, generatedAt: null, isGenerating: false, error: null });
            autoGeneratedRef.current = false;
            return;
        }
        const cached = loadCached(uid);
        if (cached) {
            setState(prev => ({
                ...prev,
                briefing: cached.briefing,
                generatedAt: cached.generatedAt,
            }));
        }
    }, [uid]);

    const generate = useCallback(async () => {
        const user = auth.currentUser;
        if (!user || allMessages.length === 0) return;

        setState(prev => ({ ...prev, isGenerating: true, error: null }));

        // Pick top messages by importance_score, deduplicated
        const messages = [...allMessages]
            .sort((a, b) => b.importance_score - a.importance_score)
            .slice(0, MAX_MESSAGES)
            .map(m => ({
                sender: m.sender,
                subject: m.subject ?? "(no subject)",
                snippet: m.content.slice(0, 300),
                timestamp: m.timestamp,
                source: m.source,
                importance_score: m.importance_score,
            }));

        try {
            const idToken = await user.getIdToken();
            const res = await fetch("/api/ai/briefing", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${idToken}`,
                },
                body: JSON.stringify({
                    date: new Date().toISOString().slice(0, 10),
                    messages,
                }),
            });

            if (!res.ok) {
                const errData = (await res.json().catch(() => ({}))) as { error?: string };
                throw new Error(errData.error ?? `API error ${res.status}`);
            }

            const data = (await res.json()) as { briefing: string; generatedAt: string };

            saveCache(user.uid, { briefing: data.briefing, generatedAt: data.generatedAt });

            setState({
                briefing: data.briefing,
                generatedAt: data.generatedAt,
                isGenerating: false,
                error: null,
            });
        } catch (err: unknown) {
            setState(prev => ({
                ...prev,
                isGenerating: false,
                error: err instanceof Error ? err.message : "Briefing generation failed",
            }));
        }
    }, [allMessages]);

    // Auto-generate once per day if no cached briefing and messages are available
    useEffect(() => {
        if (!uid || autoGeneratedRef.current) return;
        if (state.briefing) return; // already cached
        if (allMessages.length < 5) return; // not enough data yet

        autoGeneratedRef.current = true;
        generate().catch(() => {});
    }, [uid, state.briefing, allMessages.length, generate]);

    return { ...state, generate };
}
